// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/13/2024, 10:06:11 AM
const configMerger = require("/home/sumitratamang/Documents/Nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/sumitratamang/Documents/Nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sumitratamang/Documents/Nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sumitratamang/Documents/Nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sumitratamang/Documents/Nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sumitratamang/Documents/Nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sumitratamang/Documents/Nuxt/plugins/**/*.{js,ts,mjs}","/home/sumitratamang/Documents/Nuxt/composables/**/*.{js,ts,mjs}","/home/sumitratamang/Documents/Nuxt/utils/**/*.{js,ts,mjs}","/home/sumitratamang/Documents/Nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/sumitratamang/Documents/Nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/sumitratamang/Documents/Nuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
